apiVersion: v1
kind: Secret
metadata:
  name: forge-secrets
  namespace: forge
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  postgres-password: forge_secret
  minio-access-key: forge
  minio-secret-key: forge_secret
  forge-api-key: fk_change_me_to_a_random_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: forge-tls
  namespace: forge
type: kubernetes.io/tls
stringData:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: forge-ca
  namespace: forge
type: Opaque
stringData:
  ca.crt: ""
