apiVersion: v1
kind: Secret
metadata:
  name: forge-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  forge-api-key: {{ .Values.secrets.forgeApiKey | quote }}
