apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://forge-prometheus:9090
    isDefault: true
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://forge-tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://forge-loki:3100
    isDefault: false
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: \[\.+?trace_id=(\w+)\]
          name: TraceID
          url: $${__value.raw}
